name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: |
          make install
      - env:
          TEST_KEY_CODE: ${{ secrets.TEST_KEY_CODE }}
        run: |
          make test
